### PR TITLE
New version: FLINT_jll v2.7.0-dev+0

### PR DESCRIPTION
**Pull request by thofma**
UUID: e134572f-a0d5-539d-bddf-3cad8db41a82
Repo: https://github.com/oscar-system/FLINT_jll.jl
Tree: e422fbfd5f4fb21fe3c5eb931f06d0dfd2aa5d12

I hope it is OK if I abuse this registry for some non-official binary builds.

### CODE REVIEW

**Comment by benlorenz** [comment]
Sure, I created this registry only for some tests with binary build for polymake but at the moment it is unused. (polymake_jll, perl_jll and that old LoadFlint can be removed)

**Comment by thofma** [comment]
OK, great. I will probably have to do this more often, so it might be easier for you to give me push access.

**Comment by benlorenz** [comment]
> OK, great. I will probably have to do this more often, so it might be easier for you to give me push access.

done

**Comment by thofma** [comment]
Thanks!

**Pull request merged**
